apiVersion: v1
kind: Pod
metadata:
  name: csi-client
  namespace: cbt-demo
  labels:
    app: csi-client
    app.kubernetes.io/name: snapshot-metadata-lister
    app.kubernetes.io/component: tool
    app.kubernetes.io/part-of: k8s-cbt-s3mover-demo
spec:
  restartPolicy: Never
  serviceAccountName: csi-client-sa
  initContainers:
  - name: install-client
    image: golang:1.26-alpine
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - |
      apk add --no-cache git
      git clone --branch v1.0.0 --depth 1 https://github.com/kubernetes-csi/external-snapshot-metadata.git /tmp/repo
      cd /tmp/repo/tools/snapshot-metadata-lister
      CGO_ENABLED=0 go build -o /output/snapshot-metadata-lister .
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - name: shared-volume
      mountPath: /output
  containers:
  - name: run-client
    image: busybox:1.37.0
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - "tail -f /dev/null"
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: shared-volume
      mountPath: /tools
  volumes:
  - name: shared-volume
    emptyDir: {}
