kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cbt-demo
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/cbt-demo-csi
        containerPath: /var/lib/csi-hostpath-data
      - hostPath: /tmp/cbt-demo-minio
        containerPath: /mnt/minio-data
