kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cbt-demo
nodes:
  - role: control-plane
    # Enable feature gates for CBT support
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            feature-gates: "CSIVolumeSnapshotDataSource=true,VolumeSnapshotDataSource=true"
        controllerManager:
          extraArgs:
            feature-gates: "CSIVolumeSnapshotDataSource=true,VolumeSnapshotDataSource=true"
    # Mount hostPath for CSI driver storage
    extraMounts:
      - hostPath: /tmp/cbt-demo-csi
        containerPath: /var/lib/csi-hostpath-data
      - hostPath: /tmp/cbt-demo-minio
        containerPath: /mnt/minio-data
