apiVersion: v1
kind: Pod
metadata:
  name: cbt-verifier
  namespace: cbt-demo
spec:
  serviceAccountName: csi-client-sa
  initContainers:
  - name: install-tools
    image: golang:1.26
    command:
    - /bin/sh
    - -c
    - |
      apt-get update && apt-get install -y git
      git clone https://github.com/kubernetes-csi/external-snapshot-metadata.git /tmp/repo
      cd /tmp/repo/tools/snapshot-metadata-lister
      CGO_ENABLED=0 go build -o /output/snapshot-metadata-lister .
      cd /tmp/repo/tools/snapshot-metadata-verifier
      CGO_ENABLED=0 go build -o /output/snapshot-metadata-verifier .
    volumeMounts:
    - name: shared-volume
      mountPath: /output
  containers:
  - name: run-verifier
    image: busybox:1.37.0
    command:
    - /bin/sh
    - -c
    - "tail -f /dev/null"
    securityContext:
      privileged: true
    volumeMounts:
    - name: shared-volume
      mountPath: /tools
    volumeDevices:
    - name: source-device
      devicePath: /dev/source
    - name: target-device
      devicePath: /dev/target
  volumes:
  - name: shared-volume
    emptyDir: {}
  - name: source-device
    persistentVolumeClaim:
      claimName: verifier-source
  - name: target-device
    persistentVolumeClaim:
      claimName: verifier-target
