apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verifier-target
  namespace: cbt-demo
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 1Gi
