apiVersion: v1
kind: Pod
metadata:
  name: block-writer
  namespace: cbt-demo
  labels:
    app: block-writer
    app.kubernetes.io/name: block-writer
    app.kubernetes.io/component: workload
    app.kubernetes.io/part-of: k8s-cbt-s3mover-demo
spec:
  restartPolicy: Always
  automountServiceAccountToken: false
  containers:
  - name: writer
    image: busybox:1.37.0
    command:
    - /bin/sh
    - -c
    - "tail -f /dev/null"
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    volumeDevices:
    - name: data-volume
      devicePath: /dev/xvda
    securityContext:
      privileged: true
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: block-writer-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-writer-data
  namespace: cbt-demo
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 1Gi
