apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: cbt-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 10Gi
