apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: cbt-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Will use default storage class
