apiVersion: batch/v1
kind: Job
metadata:
  name: cbt-restore-list
  namespace: cbt-demo
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: list
        image: cbt-restore:latest
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/cbt-restore
        - list
        - --s3-endpoint=minio.cbt-demo.svc.cluster.local:9000
        - --s3-access-key=minioadmin
        - --s3-secret-key=minioadmin123
        - --s3-bucket=snapshots
