apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-data
  namespace: cbt-demo
  labels:
    app.kubernetes.io/name: cbt-restore
    app.kubernetes.io/component: restore
    app.kubernetes.io/part-of: k8s-cbt-s3mover-demo
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 1Gi
